# AI Research Starter Learning Notes

这是我的第一份 AI 学习笔记，用来记录目前已经完成的 Python、数据分析和机器学习练习。

Notebook 的特点是可以同时写文字和运行代码，所以很适合做实验记录。

## 1. Project Structure / 项目结构

目前项目结构：

- `data/`: 存放数据文件，比如 CSV。
- `src/`: 存放 Python 脚本。
- `notebooks/`: 存放学习笔记和实验记录。
- `outputs/`: 存放程序生成的报告、表格和图片。
- `requirements.txt`: 记录项目依赖。

我学到的核心习惯：数据、代码、输出要分开放。

## 2. Grade Analysis / 成绩分析

我先用 Python 自带的 `csv` 模块读取学生成绩，然后又学习了用 `pandas` 处理表格数据。

练习过的内容：

- 读取 CSV 文件
- 计算平均分、最高分、最低分
- 按成绩排序
- 生成排名表
- 保存 CSV 结果
- 用 matplotlib 画柱状图

In [1]:
import pandas as pd

students_df = pd.read_csv("../data/students.csv")
students_df

    name  score
0  Alice     85
1    Bob     92
2  Cindy     78
3  David     88
4    Eva     97

In [2]:
average_score = students_df["score"].mean()
highest_score = students_df["score"].max()
lowest_score = students_df["score"].min()

average_score, highest_score, lowest_score

(np.float64(88.0), np.int64(97), np.int64(78))

In [3]:
ranking = students_df.sort_values(by="score", ascending=False).reset_index(drop=True)
ranking["rank"] = range(1, len(ranking) + 1)
ranking[["rank", "name", "score"]]

   rank   name  score
0     1    Eva     97
1     2    Bob     92
2     3  David     88
3     4  Alice     85
4     5  Cindy     78

## 3. Score Prediction / 分数预测

我训练了第一个机器学习模型：根据学习时间预测考试分数。

这是一个回归任务，因为模型要预测的是一个具体数字。

重要概念：

- `X`: 特征，也就是模型输入。
- `y`: 标签，也就是模型要预测的目标。
- `fit`: 训练模型。
- `predict`: 使用模型预测。
- `train_test_split`: 划分训练集和测试集。
- `mean_absolute_error`: 平均绝对误差，用来评估模型预测差多少。

In [4]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

scores_df = pd.read_csv("../data/study_scores.csv")
scores_df

   study_hours  score
0            1     50
1            2     55
2            3     65
3            4     70
4            5     75
5            6     82
6            7     88
7            8     93

In [5]:
X = scores_df[["study_hours"]]
y = scores_df["score"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

test_predictions = model.predict(X_test)
mae = mean_absolute_error(y_test, test_predictions)

round(mae, 2)

1.38

In [6]:
new_data = pd.DataFrame({"study_hours": [9]})
predicted_score = model.predict(new_data)[0]
predicted_score = min(predicted_score, 100)

round(predicted_score, 2)

np.float64(99.76)

## 4. Git Workflow / Git 工作流程

我练习过的 Git 日常流程：

```powershell
git status
git add .
git commit -m "describe the change"
git push
```

我的理解：Git 就像给项目存档，GitHub 就像把存档同步到云端。

## 5. Next Steps / 下一步

接下来可以继续学习：

- Jupyter Notebook 的基本操作
- 分类任务 classification
- 鸢尾花数据集 Iris dataset
- 模型准确率 accuracy
- 混淆矩阵 confusion matrix